// NAVIGATION
export const NAV_LINKS = [
    { href: '/', key: 'home', label: 'Home' },
    { href: '/about', key: 'about', label: 'About' },
    { href: '/internship', key: 'internship', label: 'Internships' },
    { href: '/services', key: 'services', label: 'Services' },
    { href: '/announcement', key: 'announce', label: 'Announcement' },
    { href: '/contact', key: 'contact_us', label: 'Contact' },
  ];

export const INTERNSHIP_DETAIL = [
  {
    href:'/',
    key: 'web',
    alt: 'web_development',
    image_url: '/web.png',
    title: 'Web Development Intern | Batch 3',
    detail1: 'Perks :',
    detail2: '1. Offer Letter',
    detail3: '2. Internship Completion Certificate',
    detail4: '3. Best Performance Certificate',
    detail5: '4. Letter of Recommendation (Charges Applicable Rs. 200)',
    type: 'Free',
  },
  {
    href:'/',
    key: 'java',
    alt: 'java_development',
    image_url: '/java.png',
    title: 'Java Development Intern | Batch 3',
    detail1: 'Perks :',
    detail2: '1. Offer Letter',
    detail3: '2. Internship Completion Certificate',
    detail4: '3. Best Performance Certificate',
    detail5: '4. Letter of Recommendation (Charges Applicable Rs. 200)',
    type: 'Free',
  },
  {
    href:'/',
    key: 'python',
    alt: 'python_development',
    image_url: '/python.png',
    title: 'Python Development | Batch 3',
    detail1: 'Perks :',
    detail2: '1. Offer Letter',
    detail3: '2. Internship Completion Certificate',
    detail4: '3. Best Performance Certificate',
    detail5: '4. Letter of Recommendation (Charges Applicable Rs. 200)',
    type: 'Free',
  },
  {
    href:'/',
    key: 'dsml',
    alt: 'dsml',
    image_url: '/dsml.jpg',
    title: ' Data Science & Machine Learning Intern | Batch 3',
    detail1: 'Perks :',
    detail2: '1. Offer Letter',
    detail3: '2. Internship Completion Certificate',
    detail4: '3. Best Performance Certificate',
    detail5: '4. Letter of Recommendation',
    type: 'Free',
  },
];