import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    template: '%s | Code Crafters Community',
    default: 'Code Crafters Community',
  },
  description: 'Generated By Code Crafters Community',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body>
        <main className="relative overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
